### PR TITLE
Don't use YaruSliderSecondary widget

### PR DESCRIPTION
**Pull request by mivoligo**
Removed use of the YaruSliderSecondary from A11y page UI.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thanks @mivoligo !
I think the test is failing because pubspec.lock points to the wrong yaru_widgets version where the enabled property was not there yet :thinking: That would mean that I committed the wrong one which would be weird because I needed the most recent versions for my builds to work. Does it work for you locally?

**Comment by mivoligo** [comment]
It worked locally. I had to run pub upgrade though.

**Comment by mivoligo** [comment]
hmmm... I see the `resolved-ref` is the same in my lock file: `resolved-ref: f93fbba83b25265c9941ef59d5eb6bbeafc0eaa0` and the file is actually not changed compared to master branch.

**Comment by mivoligo** [comment]
I've recreated the lock file. Not sure why it worked for me.

**Pull request merged**
