### PR TITLE
Use YaruSimpleDialog

### LINKED ISSUE #209: SimpleDialog widget miss a close button
I know I can close the dialog by click outside, but I always feel uncomfortable when a dialog don't have a close button (and I think some other people can also be like me).

I propose to create a `YaruSimpleDialog` widget like this (this will also allow to centralise padding infos):

Capture d’écran du 2021-12-20 00-30-50

### PR DESCRIPTION
**Pull request by Jupi007**
Capture d’écran du 2021-12-20 21-34-32

Closes #209

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Awesome!

There should be some more I think
Bluetooth and WiFi and hmmmm let's see

**Comment by Jupi007** [comment]
I only replaced `SimpleDialog` with `YaruSimpleDialog`. I think you are talking about `AlertDialog`.

**Comment by Feichtmeier** [comment]
Right - don't we want the close button there, too? No strong opinion

**Comment by Jupi007** [comment]
I think it is preferable to have a close button on each dialog. So we also need a `YaruAlertDialog`.

If you're okay with the changes here, feel free to merge :)

**Comment by Feichtmeier** [comment]
Great idea with the YaruAlertDialog
you could include an elevated button and a outlined button "cancel" or something :)

**Pull request merged**
