### PR TITLE
Add HostnameService for the Info page

### PR DESCRIPTION
**Pull request by jpnurmi**
A helper service that can get and set the system hostname. The "pretty" hostname is preferred but the dynamic hostname is used as a fallback. When setting a hostname, a sanitized version of the provided value is set as the static hostname.

### Example:

```dart
class InfoModel extends ChangeNotifier {
  InfoModel([HostnameService? service])
      : _service = service ?? HostnameService();

  final HostnameService _service;

  Future<void> init() => _service.init().then((_) => notifyListeners());

  String get hostname => _service.hostname;
  String get staticHostname => _service.staticHostname;

  void setHostname(String hostname) {
    _service.setHostname(hostname).then((_) => notifyListeners());
  }

  @override
  void dispose() {
    _service.dispose();
    super.dispose();
  }
}

class InfoPage extends StatefulWidget {
  const InfoPage({Key? key}) : super(key: key);

  static Widget create(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => InfoModel(),
      child: const InfoPage(),
    );
  }

  @override
  State<InfoPage> createState() => _InfoPageState();
}

class _InfoPageState extends State<InfoPage> {
  final _controller = TextEditingController();

  @override
  void initState() {
    super.initState();

    final model = context.read<InfoModel>();
    model.init().then((_) {
      _controller.value = TextEditingValue(
        text: model.hostname,
        selection: TextSelection.collapsed(offset: model.hostname.length),
      );
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final model = context.watch<InfoModel>();
    return Scaffold(
      appBar: AppBar(
        title: Text('${model.hostname} (${model.staticHostname})'),
      ),
      body: Center(
        child: TextField(controller: _controller),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => model.setHostname(_controller.value.text),
        child: const Icon(Icons.check),
      ),
    );
  }
}
```
Screenshot from 2021-09-17 22-47-59

### CODE REVIEW

**Review by Jupi007 — APPROVED** [review]
Awesome, thank you very much!

Reading the code, it looks good for me. But you maybe should ask somebody else just in case because I'm still a beginner with dart/flutter :)

**Comment by Jupi007** [comment]
@jpnurmi I tested your example code but it throw an error:

```
Error: Could not find the correct Provider<InfoModel> above this InfoPage Widget
```

**Comment by jpnurmi** [comment]
You can use the static `InfoPage.create(context)` to create an instance of the page together with its model.

**Comment by jpnurmi** [comment]
I used it like this in the minimal test app I created for developing the service:
```
import 'package:flutter/material.dart';
import 'package:yaru/yaru.dart' as yaru;

import 'hostname_page.dart';

void main() => runApp(const HostnameApp());

class HostnameApp extends StatelessWidget {
  const HostnameApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: yaru.lightTheme,
      darkTheme: yaru.darkTheme,
      home: InfoPage.create(context),
    );
  }
}
```

**Comment by jpnurmi** [comment]
Here's a complete example: https://github.com/jpnurmi/flutter_hostname

**Comment by Jupi007** [comment]
It works, thanks :)

**Pull request merged**
