### PR TITLE
Add icons to power profile section

### PR DESCRIPTION
**Pull request by Jupi007**
A small PR to add some colored icons to the power profile section :)

Capture d’écran du 2022-03-12 22-00-53

### CODE REVIEW

**Review by Feichtmeier — APPROVED** [review]
Fantastic, thanks!

**Comment by Jupi007** [comment]
The CI fail cause to files I didn't edited 🤔
Should I still merge?

**Comment by Feichtmeier** [comment]
uhm... where does this come from Oo

```
warning - lib/view/pages/bluetooth/bluetooth_device_model.dart:88:30 - The '!' will have no effect because the receiver can't be null. Try removing the '!' operator. - unnecessary_non_null_assertion
   info - lib/services/power_settings_service.dart:80:16 - This function has a nullable return type of 'FutureOr<int?>', but ends without returning a value. Try adding a return statement, or if no value is ever returned, try changing the return type to 'void'. - body_might_complete_normally_nullable
   info - lib/services/power_settings_service.dart:87:27 - The exception variable 'e' isn't used, so the 'catch' clause can be removed. Try removing the catch clause. - unused_catch_clause
   ```
   
   oh... it was changed in the the displays PR oO

**Comment by Feichtmeier** [comment]
Yes merge, I fix it later

**Pull request merged**
