### PR TITLE
dock assets for other positions

### PR DESCRIPTION
**Pull request by Muqtxdir**
sorry for the delay, this PR adds assets for right and bottom dock and panel positions

### changes made:

- [x] separated appearance and multitasking assets.
    - [x] Multitasking:
       - [x] active-screen-edges-dock-mode: `-bottom, -left, -right`
       - [x] active-screen-edges-panel-mode: `-bottom, -left, -right`
       - [x] hot-corner-dock-mode: `-bottom, -left, -right`
       - [x] hot-corner-panel-mode: `-bottom, -left, -right`
       - [x] workspaces-dock-mode: `-bottom, -left, -right`
       - [x] workspaces-panel-mode: `-bottom, -left, -right`
       
    - [x] Appearance:
       - [x] auto-hide-dock-mode: `-bottom, -left, -right`
       - [x] auto-hide-panel-mode: `-bottom, -left, -right`
       - [x] dock-mode: `-bottom, -left, -right`
       - [x] panel-mode: `-bottom, -left, -right`
   
issue: #229

### CODE REVIEW

**Comment by Muqtxdir** [comment]
@mivoligo should I also consider doing the same and add various other position assets for `multitasking-panel` ?

**Comment by mivoligo** [comment]
> @mivoligo should I also consider doing the same and add various other position assets for `multitasking-panel` ?

That would be awesome! Thanks :slightly_smiling_face:

**Comment by Muqtxdir** [comment]
> That would be awesome! Thanks

done and made some re-organisation of assets, but the **Flutter CI / build** is failing due the change in assets-locations.

**Comment by Muqtxdir** [comment]
@Jupi007 could you in your free-time try to minimize the size of the assets

**Comment by mivoligo** [comment]
Great! I've no idea about CI settings, let's wait for @Feichtmeier to fix it :smile:

**Comment by Feichtmeier** [comment]
> > That would be awesome! Thanks
> 
> done and made some re-organisation of assets, but the **Flutter CI / build** is failing due the change in assets-locations.

you only need to adapt the lines in pubspec.yaml

**Comment by Feichtmeier** [comment]
https://github.com/Feichtmeier/settings/blob/6514ff26ab5b408fa2b4013a3e5ddb916eac6991/pubspec.yaml#L66-L72

And thank you very much for this!!!

**Comment by Feichtmeier** [comment]
merging this could be problematic as it would leave master in a not working state
can I push into this branch @Muqtxdir ?

**Comment by Jupi007** [comment]
@Muqtxdir I optimized all assets.

Sorry I messed up due to VScode, I clicked by mistake on the Pull/Push button.
Can you check if I didn't break things?

**Comment by Muqtxdir** [comment]
thanks @Jupi007 for the optimization of assets. 

> merging this could be problematic as it would leave master in a not working state
can I push into this branch @Muqtxdir ?

ok, makes sense :+1:

**Comment by Feichtmeier** [comment]
@Muqtxdir updated the branch from master and changed the paths for the "old" assets

Using all the new ones will require a bit more time (need to check which asset to use in some helper functions etc)

Let's merge this nice work for now, thank you very much! (also thank you @Jupi007  and @mivoligo for helping)

**Pull request merged**
