### PR TITLE
Upgrade from Dart 2.12 to 2.15

### PR DESCRIPTION
**Pull request by jpnurmi**
Dart 2.15 has built-in string <-> enum conversions, which comes handy
when migrating from GSettings 0.1 to 0.2 (#183).

https://medium.com/dartlang/dart-2-15-7e7a598e508a#107a

### CODE REVIEW

**Comment by jpnurmi** [comment]
NOTE: requires the latest stable Flutter 2.8

**Comment by Feichtmeier** [comment]
Thanks 👍😊

Is it ready to merge?

**Comment by jpnurmi** [comment]
It's green and ready to go now. Just needed the CI update.

**Comment by Feichtmeier** [comment]
Thank you very much @jpnurmi !

**Pull request merged**
