### PR TITLE
Move to models

### PR DESCRIPTION
**Pull request by mivoligo**
Working on issue #27

### CODE REVIEW

**Comment by jpnurmi** [comment]
Hi, could you push separate small PRs for the preparational widget and schema changes and anything else that isn't strictly about the view-model split, please?

**Comment by jpnurmi** [comment]
Even each screen could be separated and reviewed in parallel without blocking each other. Smaller PRs with less noise are pleasant to review and reduce the risk of missing things. :wink:

**Comment by mivoligo** [comment]
@jpnurmi thanks for the tips. I'll try to do that. 
Sorry but I'm not sure what do you mean by the _preparational widget_

**Comment by jpnurmi** [comment]
I meant splitting off any changes that are preparing for the final view model changes. Basically, anything that can be done as standalone separate steps.

I took only a brief look but I think I saw some new widgets added, others renamed, and constants being moved around, for example. All of which is probably fine, but adds plenty of extra diff to the actual changes.

I promised to help reviewing, and it looks good overall. 👍 It's not my project and I'm not confident reviewing a large PR that changes the entire project, though. 🙂

**Comment by mivoligo** [comment]
OK, I get it now. Thanks for taking your time to help with the project :)

**Pull request closed without merging**
