### PR TITLE
Brightness sliders

### LINKED ISSUE #205: Power page crash due to Power.Keyboard property
**Note:** I'm using a desktop computer without any control of brightness.

It looks like the app crash because I don't have the `org.gnome.SettingsDaemon.Power.Keyboard` schema installed.

```
DBusFailedException (org.freedesktop.DBus.Error.Failed: Failed to get property Brightness on interface org.gnome.SettingsDaemon.Power.Keyboard)
```

_In `power_settings_service.dart` line 80._

@Feichtmeier I hope this one is not duplicated 😅

### PR DESCRIPTION
**Pull request by mivoligo**
An attempt to fix bug #205
It works fine when I tested but not sure what we should do in the catch part of the try catch bloc :)

Closes #205

### CODE REVIEW

**Comment by Jupi007** [comment]
I'm trying to build and run this branch but I can't because of unexisting `YaruSliderSecondary`.
I tried to run pub get and upgrade I also removed `.dart_tools` and `pubspeck.lock` but the problem is still here :/

**Comment by Feichtmeier** [comment]
rightclick on pubspec.yaml and chose upgrade, after then pub get

**Comment by Jupi007** [comment]
@Feichtmeier Was still not working after that. So I removed the repo, re-cloned, a little `pub get` and it works 😅

@mivoligo Your patch work :) Now I see the slider disabled. Thanks :)

**Comment by Feichtmeier** [comment]
Let me check if it still works for a computer WITH a keyboard :D

**Comment by Jupi007** [comment]
> Let me check if it still works for a computer WITH a keyboard (with lightning) :D

Could be a good idea 😅

**Comment by mivoligo** [comment]
@Jupi007 does your screen brightness slider work properly now?

**Comment by mivoligo** [comment]
hmm... I thought you have "screen" brightness but not "keyboard" brightness. Sorry for misunderstanding :smile:

**Comment by Jupi007** [comment]
No problem :)

**Comment by Feichtmeier** [comment]
Nope does not work when you got a keyboard brightness slider but your laptop is closed:

grafik

```
Launching lib/main.dart on Linux in debug mode...
Connecting to VM Service at ws://127.0.0.1:34449/_Ozb1WrbQn4=/ws

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building LayoutBuilder:
'package:flutter/src/material/slider.dart': Failed assertion: line 147 pos 15: 'value >= min && value <= max': is not true.

The relevant error-causing widget was
YaruSliderRow
When the exception was thrown, this was the stack
#2      new Slider
#3      YaruSliderRow.build.<anonymous closure>
#4      _LayoutBuilderElement._layout.layoutCallback
#5      BuildOwner.buildScope
#6      _LayoutBuilderElement._layout
#7      RenderObject.invokeLayoutCallback.<anonymous closure>
#8      PipelineOwner._enableMutationsToDirtySubtrees
#9      RenderObject.invokeLayoutCallback
#10     RenderConstrainedLayoutBuilder.rebuildIfNecessary
#11     _RenderLayoutBuilder.performLayout
#12     RenderObject.layout
#13     ChildLayoutHelper.layoutChild
#14     RenderFlex._computeSizes
#15     RenderFlex.performLayout
#16     RenderObject.layout
#17     ChildLayoutHelper.layoutChild
#18     RenderFlex._computeSizes
#19     RenderFlex.performLayout
#20     RenderObject.layout
#21     RenderPadding.performLayout
#22     RenderObject.layout
#23     RenderConstrainedBox.performLayout
#24     RenderObject.layout
#25     ChildLayoutHelper.layoutChild
#26     RenderFlex._computeSizes
#27     RenderFlex.performLayout
#28     RenderObject.layout
#29     ChildLayoutHelper.layoutChild
#30     RenderFlex._computeSizes
#31     RenderFlex.performLayout
#32     RenderObject.layout
#33     RenderPadding.performLayout
#34     RenderObject.layout
#35     RenderProxyBoxMixin.performLayout
#36     RenderObject.layout
#37     RenderConstrainedBox.performLayout
#38     RenderObject.layout
#39     RenderPadding.performLayout
#40     RenderObject.layout
#41     ChildLayoutHelper.layoutChild
#42     RenderFlex._computeSizes
#43     RenderFlex.performLayout
#44     RenderObject.layout
#45     RenderPadding.performLayout
#46     RenderObject.layout
#47     _RenderSingleChildViewport.performLayout
#48     RenderObject._layoutWithoutResize
#49     PipelineOwner.flushLayout
#50     RendererBinding.drawFrame
#51     WidgetsBinding.drawFrame
#52     RendererBinding._handlePersistentFrameCallback
#53     SchedulerBinding._invokeFrameCallback
#54     SchedulerBinding.handleDrawFrame
#55     SchedulerBinding._handleDrawFrame
#59     _invoke (dart:ui/hooks.dart:151:10)
#60     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#61     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/material/slider.dart': Failed assertion: line 147 pos 15: 'value >= min && value <= max': is not true.
The relevant error-causing widget was
YaruSliderRow
════════════════════════════════════════════════════════════════════════════════
```

I will push into this branch if this is okay @mivoligo ?

**Comment by Feichtmeier** [comment]
ya

@mivoligo fixed and tested (sorry I just pushed the fix ^^ :angel: )

**Comment by Feichtmeier** [comment]
@Jupi007 to also fix #205 I use the fix for the screen brightness also for the keyboard brightness (if the value is -1, disable it and fake set the value to 0)

Could you see if this fixes it for you? BEcause even though closing the laptop lid makes me unable to change the keyboard brightness it is still somehow there and even the gnome shell OSD pops up. So someone without a laptop needs to test this again ^^

**Comment by Jupi007** [comment]
@Feichtmeier I have now both keyboard and screen brightness disabled :)
No more issue, it's fixed!

**Comment by Feichtmeier** [comment]
@Jupi007 thanks for testing!

**Pull request merged**
