### PR TITLE
Alternative widgets ii

### PR DESCRIPTION
**Pull request by mivoligo**
This time without renaming :)

I haven't touched models much to change getters to be able return null. For now I tested it mostly on A11y page which has getters returning null already.
For a lot of YaruRow widgets, I just used `enable: true` without looking deeper in the model.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
> This time without renaming :)
> 
> I haven't touched models much to change getters to be able return null. For now I tested it mostly on A11y page which has getters returning null already.
> For a lot of YaruRow widgets, I just used `enable: true` without looking deeper in the model.

Thanks and sorry for the double work

It's a nice idea to leave out the models mostly

I'll test it today

**Comment by Feichtmeier** [comment]
Tested eaach page locally. Couldn't fins any issue so far :thumbs_up:
What's the plan for those widgets where you've assumed enabled: true without checking the models? I understand that we can keep this for widgets that are in a list (wifi accent point tile / bluetooth device row) and only instatiated if the resouce is availible. But for the rest we could indeed look up each model everywhere. Or we could split this into a second PR (I could do it)

**Comment by mivoligo** [comment]
I'd go for a separate PR. 

Another question: should I do a PR against YaryWidgets before merging this one or later on and for now we use my repo link in the pubspec?

**Comment by Feichtmeier** [comment]
> I'd go for a separate PR.
> 
> Another question: should I do a PR against YaruWidgets before merging this one or later on and for now we use my repo link in the pubspec?

Yes, do the yaru_widgets first, then we change do not need to change the pubspec here :)

**Comment by Feichtmeier** [comment]
Thanks is it ready to merge?

**Comment by mivoligo** [comment]
I think so, sorry for not changing the status :smile:

**Review by Feichtmeier — APPROVED** [review]

**Pull request merged**
