### PR TITLE
Make brightness sliders movable

### PR DESCRIPTION
**Pull request by mivoligo**

### CODE REVIEW

**Comment by mivoligo** [comment]
There's still some problems with those sliders. I can only test the screen brightness slider but I noticed it doesn't update its position when clicking somewhere on the track even though the screen brightness is updating. The other issue is that the slider doesn't update when I change the brightness from outside this app.

**Comment by Feichtmeier** [comment]
I don't think this change is needed. The changes are received via stream change subscriptions whch include the notifyListeners()
https://github.com/Feichtmeier/settings/blob/d29d58d2d355026051c333d09926f21194e185b7/lib/view/pages/power/power_settings_model.dart#L37-L55

Also changes made in the app are received in GCC and the other way round:

ya

**Comment by mivoligo** [comment]
Hmm... so something must be wrong with my laptop. Without this change the screen brightness slider does not move at all for me even though the brightness of the screen changes.

**Comment by Feichtmeier** [comment]
> Hmm... so something must be wrong with my laptop. Without this change the screen brightness slider does not move at all for me even though the brightness of the screen changes.

I wouldn't assume this as the only reason but maybe yes
At least it works for me fine

Does it work for you from GCC? I mean do the handles work and are synced with the GNOME shell slider?

**Comment by mivoligo** [comment]
> Does it work for you from GCC? I mean do the handles work and are synced with the GNOME shell slider?

It does not, sadly.

**Pull request closed without merging**
