### PR TITLE
Replace almost all default icons by yaru ones

### PR DESCRIPTION
**Pull request by Jupi007**
Some icons are still missing (wifi, appearance, ...), but here is a preview:

Capture d’écran du 2021-07-05 22-56-08

I'll add missing ones tomorrow :)

### CODE REVIEW

**Review by Feichtmeier — APPROVED** [review]

**Comment by Jupi007** [comment]
Capture d’écran du 2021-07-07 19-13-01

I added missing icons.

**Comment by Feichtmeier** [comment]
Thank you @Jupi007 ! Looks really amazing like a proper yaru style app now <3

**Comment by Jupi007** [comment]
It's indeed beautiful now with Yaru icons 😃

**Comment by Jupi007** [comment]
@Feichtmeier Note: I let you update the README gif, which is now outdated.

**Pull request merged**
