### PR TITLE
Add App theme test

### PR DESCRIPTION
**Pull request by shan-shaji**

### CODE REVIEW

**Comment by shan-shaji** [comment]
Requesting review @jpnurmi

**Comment by Feichtmeier** [comment]
Hey @shan-shaji 
Sorry for not answering for so long.
Could you rebase this PR on master? Should be only pubspec.lock that is now not anymore in the repo

**Comment by shan-shaji** [comment]
Hey @Feichtmeier , Yeah sure, I will rebase the PR

**Comment by Feichtmeier** [comment]
@shan-shaji thank you very much! :tada: 

Could you also remove the pubspec.lock from this PR? I moved it to .gitignore. Wondering why it popped up for you :thinking:

**Comment by shan-shaji** [comment]
Hey @Feichtmeier, I have updated the file

**Pull request merged**
