### PR TITLE
Add model for app notifications

### PR DESCRIPTION
**Pull request by jpnurmi**

### CODE REVIEW

**Review by Feichtmeier — APPROVED** [review]
Works (ofc it does ;) )
worksssss

**Comment by Feichtmeier** [comment]
Eventually we could find a way to exclude apps that are no longer installed (in my example firefox deb)

**Comment by jpnurmi** [comment]
This PR doesn't introduce any functional changes. The motivation was to remove the last use of `SingleGsettingRow` which makes it easier to eventually port to dbus.dart 0.2.0. :brain:

**Comment by Feichtmeier** [comment]
Sure thing was just a note :) merging ! Thank you very much :tada:

**Pull request merged**
