### PR TITLE
Add search feature

### LINKED ISSUE #28: Missing feature: search settings page
I know it's just a WIP placeholder, but the large **Settings** label should be replaced with a textfield / searchfield.

image

When the field isn't active, a grayed out **Search** label is visible. 

image

As the user enters a query, matching results are displayed in the sidebar below (or as a dropdown)

image

### PR DESCRIPTION
**Pull request by Feichtmeier**
saarch

Closes #28

### CODE REVIEW

**Comment by mivoligo** [comment]
Two things I've noticed after short test:
1. there's no way to dismiss the search dialog without selecting an option.
2. 1 second delay is too much when scrolling between entries which are close to each other. It looks laggy.

**Comment by Feichtmeier** [comment]
> Two things I've noticed after short test:
> 
>     1. there's no way to dismiss the search dialog without selecting an option.
> 
>     2. 1 second delay is too much when scrolling between entries which are close to each other. It looks laggy.

There was still the ESC option but you are right, too hidden =)
300 mS now and a close button:

y

**Comment by mivoligo** [comment]
300 ms is much better :+1: 
Close button is OK, maybe we could also dismiss it by clicking outside of the window. What do you think about eventually making a standard popup dialog widget? I used a lot of dialogs in a11y page.

**Comment by Feichtmeier** [comment]
> 300 ms is much better +1
> Close button is OK, maybe we could also dismiss it by clicking outside of the window. What do you think about eventually making a standard popup dialog widget? I used a lot of dialogs in a11y page.

Great :)

I think the click outside to close it problematic since it could happen by mistake. But let's discuss this in a separate issue as you said we could try a general dialog style

**Comment by mivoligo** [comment]
Just looked at the code. I guess we need 'milliseconds', not 'microseconds' :smile:

**Comment by Feichtmeier** [comment]
woopsie :laughing: 

now this should be 300 

mS

**Comment by mivoligo** [comment]
looks like controllers are not disposed. Sorry, I should have noticed earlier.

**Comment by Feichtmeier** [comment]
np just wanted to work on a fresh master, sorry for the hurry - kinda idiotic from me

I fix the dispose in a new PR
the scrollcontroller can't be disposed

**Pull request merged**
