### PR TITLE
Alternative widgets

### PR DESCRIPTION
**Pull request by mivoligo**
I've made this based on the refactored Yaru widgets. pubspec points to my repo with the widgets. Please test and check for problems.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thanks! 
This will probably take a bit time to review as I need to test each page and inside each action 😁

**Comment by Feichtmeier** [comment]
Hm...

allowing null for the getters sounds good 

but what about rather changing only the onTap()... onChanged() etc callbacks to be null if the getters return null instead of using the enabled property? I mean we could do both but I just remembered that flutter sets the widgets to disabled if the callbacks are null - at least for default widgets. I think custom widgets created with inkwells do not have this, right?

**Comment by Feichtmeier** [comment]
https://github.com/mivoligo/yaru_widgets.dart/blob/59d801ca43b3d4426c3a15a4fd77cb1b5b88fbc3/lib/src/yaru_switch_row.dart#L54

:+1:

**Comment by Feichtmeier** [comment]
Could you maybe leave out the renaming of the trailing widget into main widget for this pull request? 
We can see if it's needed after this one
Makes it easier to focus on the issue of having disabled widgets :)

**Comment by mivoligo** [comment]
I'll try to do that :)

**Comment by mivoligo** [comment]
I'll  close this PR and create a new one

**Pull request closed without merging**
