### PR TITLE
Update Keyboard Page

### PR DESCRIPTION
**Pull request by Feichtmeier**
WIP
grafik
grafik

- [x] Consolidate the keyboard settings and the keyboard shortcuts page in a tabbed view
- [x] use a model for each different section
- [ ] add more keyboard shortcuts
- [ ] grab the keyboard before recording shortcuts

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@jpnurmi 

Do you have any idea what the hell this type is? Some sort of collection but I can't get it right

grafik

**Comment by jpnurmi** [comment]
The loop assumes that each element in the array is a string, but the type is not an array of strings. The type is an array of structs that each contains two strings. If I remember correctly, dbus.dart presents structs as iterables. So it's something like `Iterable<Iterable<String>>` (not `Iterable<String>`). Therefore you cannot use `stringArrayValue()` but you can use `getValue<Iterable>()` instead. Then in the loop, each element is an iterable with two elements.

**Comment by Feichtmeier** [comment]
> The loop assumes that each element in the array is a string, but the type is not an array of strings. The type is an array of structs that each contains two strings. If I remember correctly, dbus.dart presents structs as iterables. So it's something like `Iterable<Iterable<String>>` (not `Iterable<String>`). Therefore you cannot use `stringArrayValue()` but you can use `getValue<Iterable>()` instead. Then in the loop, each element is an iterable with two elements.

Thanks!
getValue<Iterable> did the trick, even though I needed to use Iterable? as the type
grafik

**Comment by Feichtmeier** [comment]
@jpnurmi any more tip on the dbus types here?

https://github.com/Feichtmeier/settings/blob/4c633880414521968f456030a821757dbef0f31a/lib/view/pages/keyboard/keyboard_settings_page.dart#L55

--->

https://github.com/Feichtmeier/settings/blob/4c633880414521968f456030a821757dbef0f31a/lib/view/pages/keyboard/input_source_model.dart#L32

I still get type errors :(
Gett works, setter does not 

```bash
Restarted application in 687ms.
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Unsupported operation: Unsupported type: Iterable<dynamic>
#0      Settings.setValue
#1      InputSourceModel.sources=
#2      InputSourceSelectionSection.build.<anonymous closure>
#3      SliverReorderableListState._dropCompleted
#4      _DragInfo._dropCompleted
#5      _DragInfo.startDrag.<anonymous closure>
#6      AnimationLocalStatusListenersMixin.notifyStatusListeners
#7      AnimationController._checkStatusChanged
#8      AnimationController._tick
#9      Ticker._tick
#10     SchedulerBinding._invokeFrameCallback
#11     SchedulerBinding.handleBeginFrame.<anonymous closure>
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#13     SchedulerBinding.handleBeginFrame
#14     SchedulerBinding._handleBeginFrame
#15     _rootRunUnary (dart:async/zone.dart:1442:13)
#16     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#18     _invoke1 (dart:ui/hooks.dart:170:10)
#19     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:286:5)
#20     _beginFrame (dart:ui/hooks.dart:104:31)
Reloaded 5 of 1980 libraries in 738ms.
```

**Comment by jpnurmi** [comment]
In short, D-Bus doesn't take Dart types. The value value that was queried from D-Bus and converted to a Dart value, needs to be converted back to a DBusValue.

Check the SettingsService.setValue() helper function that can convert most common Dart types to DBusValues. It hasn't been taught to handle nested string iterables or lists of structs.

**Comment by jpnurmi** [comment]
It might be good to start by replacing those dynamic types with the exact types to get a better understanding of what exact types they are. 🙂

**Comment by jpnurmi** [comment]
I'm answering from phone but I remember correctly, the types were `DBusArray(DBusStruct))` <-> `Iterable<Iterable<String>>` that you need to convert back and forth.

**Comment by Feichtmeier** [comment]
Ok, did not work at all. Debugging always shows it is getting the "type" `MappedListIterable<DBusValue, dynamic>` which I can not create with any constructor I have found.
Does this maybe need a change in the SettingsService?
The setter only cares for DBusBoolean, DBusInt32, DBusDouble, DBusString and DBusArray but not for DBusStructs

I pause the work on the PR until you have time and maybe push a fix for the model setter / getter? No hurry got enough other pages to do ^^

**Comment by jpnurmi** [comment]
> Debugging always shows it is getting the "type" `MappedListIterable<DBusValue, dynamic>` which I can not create with any constructor I have found.

Think of `MappedListIterable<DBusValue, dynamic>` as `Iterable<dynamic>`.

It's a Dart implementation detail for the result of calling `Iterable.map()` to convert `Iterable<DbusValue>` to `Iterable<dynamic>`, thus the name "mapped iterable<from, to>".

**Comment by jpnurmi** [comment]
- dbus.dart operates with DBusValues, not with primitive Dart values
- SettingsService adds convenience API to be able to pass the most common Dart types that can be easily mapped to DBusValues (bool instead of DBusBoolean, int instead of DBusInt32, String instead of DBusString, ...)
- if you have some more complex types, such as a list of structs, you'll need to convert the values by hand. There's no generic way to convert Iterable<Iterable> to a D-Bus type because it's ambiguous. it could be DBusArray<DBusArray> or DBusArray<DBusStruct>, for example

**Comment by jpnurmi** [comment]
Examples with explicit types to make the type conversions clear:

## Reading D-Bus values from GSettings
```dart
Future<void> main(List<String> arguments) async {
  final GSettings settings = GSettings('org.gnome.desktop.input-sources');

  final DBusValue dbusValue = await settings.get('sources');
  print('${dbusValue.runtimeType}: $dbusValue');

  final DBusArray dbusArray = dbusValue as DBusArray;
  for (final DBusValue dbusArrayChild in dbusArray.children) {
    print('  - ${dbusArrayChild.runtimeType}: $dbusArrayChild');

    final DBusStruct dbusStruct = dbusArrayChild as DBusStruct;
    for (final DBusValue dbusStructChild in dbusStruct.children) {
      print('    - ${dbusStructChild.runtimeType}: $dbusStructChild');

      // final DBusString str = dbusStructChild as DBusString;
      // ...
    }
  }

  await settings.close();
}
```

## Converting D-Bus values to Dart values
```dart
Future<void> main(List<String> arguments) async {
  final GSettings settings = GSettings('org.gnome.desktop.input-sources');

  final DBusValue dbusValue = await settings.get('sources');

  final dynamic dartValue = dbusValue.toNative();
  print('${dartValue.runtimeType}: $dartValue');

  final Iterable<dynamic> dartArray = dartValue as Iterable<dynamic>;
  for (final dynamic dartArrayChild in dartArray) {
    print('  - ${dartArrayChild.runtimeType}: $dartArrayChild');

    final Iterable<dynamic> dartStruct = dartArrayChild as Iterable<dynamic>;
    for (final dynamic dartStructChild in dartStruct) {
      print('    - ${dartStructChild.runtimeType}: $dartStructChild');

      // final String str = dartStructChild as String;
      // ...
    }
  }

  await settings.close();
}
```

## Writing D-Bus values to GSettings
```dart
Future<void> main(List<String> arguments) async {
  final GSettings settings = GSettings('org.gnome.desktop.input-sources');

  final DBusStruct de = DBusStruct([DBusString('xkb'), DBusString('de')]);
  final DBusStruct us = DBusStruct([DBusString('xkb'), DBusString('us+mac')]);

  final DBusArray array = DBusArray(DBusSignature('(ss)'), [
    de,
    us,
  ]);

  await settings.set('sources', array);

  await settings.close();
}
```

**Comment by Feichtmeier** [comment]
@jpnurmi thanks for the help!

Been playing around with your code snippets.
I can get the getter working with this "classical" GSetting approach and a FutureBuilder [(last commit)](https://github.com/Feichtmeier/settings/pull/202/commits/e7ec11b25c6db6c82e972b09a19d7985852f3285)
image

```dart
  Future<List<String>?> get sources async {
    final settings = GSettings(schemaInputSources);
    final List<String>? inputTypes = [];

    final DBusArray dbusArray = await settings.get(_sourcesKey) as DBusArray;

    for (final DBusValue dbusArrayChild in dbusArray.children) {
      final DBusStruct dbusStruct = dbusArrayChild as DBusStruct;
      inputTypes?.add((dbusStruct.children[1] as DBusString).value);
    }

    await settings.close();

    return inputTypes ?? [];
  }
  ```

However, when I try to use this with your settingsservice ...

```dart
  List<String> get sources {
    final List<String>? inputTypes = [];

    final DBusValue dbusValue = _inputSourceSettings?.getValue(_sourcesKey);

    final dynamic dartValue = dbusValue.toNative();
    final Iterable<dynamic> dartArray = dartValue as Iterable<dynamic>;
    for (final dynamic dartArrayChild in dartArray) {
      final Iterable<dynamic> dartStruct = dartArrayChild as Iterable<dynamic>;
      for (final dynamic dartStructChild in dartStruct) {
        inputTypes?.add(dartStructChild);
      }
    }

    return inputTypes ?? [];
  }
  ```
a null is returned instead of the expected DBusValue

```bash
Restarted application in 556ms.

════════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown building InputSourceSelectionSection(dirty, dependencies: [_InheritedProviderScope<InputSourceModel?>]):
type 'Null' is not a subtype of type 'DBusValue'

The relevant error-causing widget was
InputSourceSelectionSection
When the exception was thrown, this was the stack
#0      InputSourceModel.sources
#1      InputSourceSelectionSection.build
#2      StatelessElement.build
#3      ComponentElement.performRebuild
#4      Element.rebuild
#5      ComponentElement._firstBuild
#6      ComponentElement.mount
#7      Element.inflateWidget
#8      Element.updateChild
#9      ComponentElement.performRebuild
#10     _InheritedProviderScopeElement.performRebuild
#11     Element.rebuild
#12     ComponentElement._firstBuild
#13     ComponentElement.mount
#14     _InheritedProviderScopeElement.mount
...     Normal element mounting (7 frames)
#21     SingleChildWidgetElementMixin.mount
#22     Element.inflateWidget
#23     MultiChildRenderObjectElement.inflateWidget
#24     MultiChildRenderObjectElement.mount
...     Normal element mounting (45 frames)
#69     Element.inflateWidget
#70     Element.updateChild
#71     SliverMultiBoxAdaptorElement.updateChild
#72     SliverMultiBoxAdaptorElement.createChild.<anonymous closure>
#73     BuildOwner.buildScope
#74     SliverMultiBoxAdaptorElement.createChild
#75     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>
#76     RenderObject.invokeLayoutCallback.<anonymous closure>
#77     PipelineOwner._enableMutationsToDirtySubtrees
#78     RenderObject.invokeLayoutCallback
#79     RenderSliverMultiBoxAdaptor._createOrObtainChild
#80     RenderSliverMultiBoxAdaptor.addInitialChild
#81     RenderSliverFixedExtentBoxAdaptor.performLayout
#82     RenderObject.layout
#83     RenderSliverEdgeInsetsPadding.performLayout
#84     _RenderSliverFractionalPadding.performLayout
#85     RenderObject.layout
#86     RenderViewportBase.layoutChildSequence
#87     RenderViewport._attemptLayout
#88     RenderViewport.performLayout
#89     RenderObject.layout
#90     RenderProxyBoxMixin.performLayout
#91     RenderObject.layout
#92     RenderProxyBoxMixin.performLayout
#93     RenderObject.layout
#94     RenderProxyBoxMixin.performLayout
#95     RenderObject.layout
#96     RenderProxyBoxMixin.performLayout
#97     RenderObject.layout
#98     RenderProxyBoxMixin.performLayout
#99     RenderObject.layout
#100    RenderProxyBoxMixin.performLayout
#101    RenderObject.layout
#102    RenderConstrainedBox.performLayout
#103    RenderObject.layout
#104    RenderPadding.performLayout
#105    RenderObject.layout
#106    ChildLayoutHelper.layoutChild
#107    RenderFlex._computeSizes
#108    RenderFlex.performLayout
#109    RenderObject.layout
#110    RenderPadding.performLayout
#111    RenderObject.layout
#112    RenderPositionedBox.performLayout
#113    RenderObject.layout
#114    _RenderSingleChildViewport.performLayout
#115    RenderObject._layoutWithoutResize
#116    PipelineOwner.flushLayout
#117    RendererBinding.drawFrame
#118    WidgetsBinding.drawFrame
#119    RendererBinding._handlePersistentFrameCallback
#120    SchedulerBinding._invokeFrameCallback
#121    SchedulerBinding.handleDrawFrame
#122    SchedulerBinding._handleDrawFrame
#126    _invoke (dart:ui/hooks.dart:151:10)
#127    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#128    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
A RenderFlex overflowed by 99250 pixels on the bottom.
The relevant error-causing widget was
Column
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
type 'MappedListIterable<DBusValue, dynamic>' is not a subtype of type 'DBusValue'
The relevant error-causing widget was
InputSourceSelectionSection
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown building InputSourceSelectionSection(dirty, dependencies: [_InheritedProviderScope<InputSourceModel?>]):
type 'MappedListIterable<DBusValue, dynamic>' is not a subtype of type 'DBusValue'

The relevant error-causing widget was
InputSourceSelectionSection
When the exception was thrown, this was the stack
#0      InputSourceModel.sources
#1      InputSourceSelectionSection.build
#2      StatelessElement.build
#3      ComponentElement.performRebuild
#4      Element.rebuild
#5      BuildOwner.buildScope
#6      WidgetsBinding.drawFrame
#7      RendererBinding._handlePersistentFrameCallback
#8      SchedulerBinding._invokeFrameCallback
#9      SchedulerBinding.handleDrawFrame
#10     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
A RenderFlex overflowed by 99250 pixels on the bottom.
The relevant error-causing widget was
Column
════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 1987 libraries in 551ms.
```

(( ignore the failed test... it's a dependency missmatch from ... will fix ))

**Comment by Feichtmeier** [comment]
Final version
grafik
grafik

will add more shortcuts in another PR, this one has already grown too big

**Pull request merged**
